version: '3.2'

services:
  server:
    build:
      context: srv/
    ports:
      - '3001:3001'
    networks:
      - devops_srv_net
    volumes:
      - type: volume
        source: srv-data
        target: /usr/src/app/logger/logs

  filebeats:
    build:
      context: filebeat/
    volumes:
      - type: volume
        source: srv-data
        target: /usr/share/logging/logs
    user: root
    networks:
      - devops_srv_net
    depends_on:
      - server

networks:
  devops_srv_net:
    driver: bridge

volumes:
  srv-data:
