apiVersion: apps/v1 #version of the API to use
kind: Deployment #what kind of object we're deploying
metadata: #information about our object we're deploying
  name: be-worker-deployment #ame of the deployment
  namespace: edu-ma2-web
  labels: #a labels on the deployments created
    owner: ramza
spec: #specifications for our object
  replicas: 1 #the number of pods that should always be running
  selector: #which pods the replica set should be responsible for
    matchLabels:
      app: be-worker-client #any pods with labels matching this I'm responsible for
  template: #the pod template that gets deployed
    metadata:
      labels: #labels on the replica set and pods created
        app: be-worker-client
    spec:
      containers:
        - name: be-worker-container #the name of the container within the pod
          image: ramza/edu-ma2-web-be-worker:latest #which container image should be pulled
          imagePullPolicy: Always
      imagePullSecrets:
        - name: edu-ma2-web-docker-registry
