Vagrant.configure("2") do |config|
	config.vm.define "elk" do |elk|
		elk.vm.box = "ubuntu/focal64"
		elk.vm.hostname = "elk"
		elk.vm.provider :virtualbox do |v|
			v.customize ["modifyvm", :id, "--memory", 2048]
		end
		elk.vm.network "private_network", ip: "192.168.10.31"
		# kibana ports
		elk.vm.network "forwarded_port", guest: 5601, host: 3003
		elk.vm.synced_folder "./provision/elk", "/vagrant"
		elk.vm.provision "shell", path: "./provision/elk/elkprovisioning.sh"
	end
	config.vm.define "database" do |database|
		database.vm.box = "ubuntu/focal64"
		database.vm.hostname = "database"
		database.vm.network "private_network", ip: "192.168.10.32"
		database.vm.network "forwarded_port", guest: 3002, host: 3002
		database.vm.synced_folder "./provision/db", "/vagrant"
		database.vm.provision "shell", path: "./provision/db/databaseprovisioning.sh"
	end
	config.vm.define "server" do |server|
		server.vm.box = "ubuntu/focal64"
		server.vm.hostname = "server"
		server.vm.network "private_network", ip: "192.168.10.33"
		# server.vm.network "forwarded_port", guest: 3001, host: 3001
		server.vm.synced_folder "./provision/srv", "/vagrant"
		server.vm.provision "shell", path: "./provision/srv/backendprovisioning.sh"
	end
	config.vm.define "client" do |client|
		client.vm.box = "ubuntu/focal64"
		client.vm.hostname = "client"
		client.vm.provider :virtualbox do |v|
			v.customize ["modifyvm", :id, "--memory", 2048]
		end
		client.vm.network "private_network", ip: "192.168.10.34"
		client.vm.network "forwarded_port", guest: 3000, host: 3000
		client.vm.synced_folder "./provision/cli", "/vagrant"
		client.vm.provision "shell", path: "./provision/cli/frontendprovisioning.sh"
	end
end