exports.UserCompleteDTO = {
  cnp: '',
  email: '',
  username: '',
  firstname: '',
  lastname: '',
  // 'password',
  date_started: null,
  date_end: null,
  position: '',
  salary: 0,
  pc: {},
  car: {},
  comments: [],
};
